all:
  vars:
    ansible_httpapi_use_proxy: false
  children:
    arista_ceos:
      vars:
        ansible_user: admin
        ansible_password: admin
      hosts:
        clab-ceos-ceos:
          ansible_host: 1.1.1.6