all:
  vars:
    ansible_httpapi_use_proxy: false
    ansible_ssh_transfer_method: paramiko
  children:
    arista_ceos:
      vars:
        ansible_user: admin
        ansible_password: admin
        ansible_become_password: admin
        ansible_connection: network_cli
        ansible_network_os: arista.eos.eos
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_host_key_checking: false
        ansible_become: true
        ansible_become_method: enable
      hosts:
        clab-ceos-ceos:
          ansible_host: 1.1.1.6