---
- name: Arista Configuration Management
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  
  vars:
    config_dir: "{{ lookup('env', 'HOME') }}/arista_configs"
    raw_configs_dir: "{{ config_dir }}/raw_configs"
    html_reports_dir: "{{ config_dir }}/html_reports"
    ssh_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    
  tasks:
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      loop:
        - "{{ config_dir }}"
        - "{{ raw_configs_dir }}"
        - "{{ html_reports_dir }}"
        
    - name: Get current date and time
      ansible.builtin.command: date
      register: timestamp
      delegate_to: localhost
      changed_when: false
      
    - name: Run show running-config | no-header command
      arista.eos.eos_command:
        commands:
          - show running-config | no-header
      register: running_config
      vars:
        ansible_connection: network_cli
        ansible_network_os: arista.eos.eos
        ansible_ssh_common_args: "{{ ssh_args }}"
        ansible_host_key_checking: false
        ansible_become: true
        ansible_become_method: enable
        
    - name: Save raw configuration
      ansible.builtin.copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ raw_configs_dir }}/{{ inventory_hostname }}_running_config_{{ timestamp }}.txt"
      delegate_to: localhost
      
    - name: Run additional show commands to extract configuration sections
      arista.eos.eos_command:
        commands:
          - show hostname
          - show vlan
          - show interfaces
          - show ip route
          - show ip bgp summary
          - show ntp status
          - show aaa
      register: show_outputs
      vars:
        ansible_connection: network_cli
        ansible_network_os: arista.eos.eos
        ansible_ssh_common_args: "{{ ssh_args }}"
        
    - name: Parse configuration sections
      ansible.builtin.set_fact:
        config_sections:
          hostname: "{{ show_outputs.stdout[0] | default('Unknown') }}"
          vlans: "{{ running_config.stdout[0] | regex_findall('vlan \\d+') }}"
          interfaces: "{{ running_config.stdout[0] | regex_findall('(?ms)interface [\\w\\d\\/]+.*?(?=!|$)') }}"
          routing: "{{ running_config.stdout[0] | regex_findall('(?ms)ip route.*?(?=!|$)') }}"
          bgp: "{{ running_config.stdout[0] | regex_findall('(?ms)router bgp.*?(?=!\\s*router|$)') }}"
          management: "{{ running_config.stdout[0] | regex_findall('(?ms)management.*?(?=!|$)') }}"
          ntp: "{{ running_config.stdout[0] | regex_findall('(?ms)ntp.*?(?=!|$)') }}"
          aaa: "{{ running_config.stdout[0] | regex_findall('(?ms)aaa.*?(?=!|$)') }}"
      
    - name: Generate HTML visualization
      ansible.builtin.template:
        src: templates/config_visualization.html.j2
        dest: "{{ html_reports_dir }}/{{ inventory_hostname }}_config_{{ timestamp }}.html"
      delegate_to: localhost
      
    - name: Display output locations
      ansible.builtin.debug:
        msg: 
          - "Raw configuration saved to {{ raw_configs_dir }}/{{ inventory_hostname }}_running_config_{{ timestamp }}.txt"
          - "HTML report generated at {{ html_reports_dir }}/{{ inventory_hostname }}_config_{{ timestamp }}.html"